name: Docker Image CI

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and push the Docker image
      run: |
        docker login --username hellodhlyn --password ${{ secrets.DOCKER_ACCESS_TOKEN }}
        docker build -t hellodhlyn/elysia:${GITHUB_REF##*/} .
        docker push hellodhlyn/elysia:${GITHUB_REF##*/}
